baseurl                  = "https://30DayChartChallenge.github.io"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "30DayChartChallenge"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "favicon.ico"
    homepage             = "main"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "<a href='https://twitter.com/30DayChartChall' target='_blank'>#30DayChartChallenge</a>"

# Metadata for Open Graph and Twitter
    description          = "30DayChartChallenge"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "30DayChartChallenge"
    # rss                = ""

[[params.mainMenu]]
    link = "twentytwo"
    text = "2022"

[[params.mainMenu]]
    link = "about"
    text = "About"

[imaging]
    quality = 75
